In [1]:
from srcmodules.Scenes import *
from srcmodules.Objects import *
from srcmodules.Actions import * 

# Object features
- Each object has functions, how we can interact with the object and change its inner logic variables.
- Each object instance has its own feasibility logic structure
- Object functions operates one level under `Actions` class. The users are triggering actions and do NOT use object functions

## Ex. 1: Put cup1 into drawer

In [4]:
drawer1 = Objects.Drawer(name='drawer1', position=[0,0,0])
drawer2 = Objects.Drawer(name='drawer2', position=[2,0,0], opened=False)
cup1 = Objects.Cup(name='cup1', position=[2,0,0])

In [5]:
drawer2.open()

(True, '')

In [6]:
drawer2.contains

[]

In [7]:
drawer2.put_in(cup1)

(True, '')

In [8]:
drawer2.contains

## Ex.2: Features showcase

In [9]:
scene = Scene(objects=[drawer1, drawer2, cup1])
scene.info

Scene info. shape: [4, 4, 4]
0. drawer1,	drawer,	[ 0.2 -0.3  0. ], semi-opened, cont: [],	|| [drawer1] >>
1. drawer2,	drawer,	[ 0.6 -0.3  0. ], opened, cont: ['cup1'],	|| [drawer2] >>
2. cup1,	cup,	[ 0.6 -0.3  0. ], empty,	|| [cup1] >>
Robot: [0.6 0.3 0.6], closed, rotation: 0, attached: -
User id: 1


In [10]:
scene.collision_free()

True

In [11]:
scene.drawer2.pick_up(scene.cup1)

(True, '')

In [12]:
scene.info

Scene info. shape: [4, 4, 4]
0. drawer1,	drawer,	[ 0.2 -0.3  0. ], semi-opened, cont: [],	|| [drawer1] >>
1. drawer2,	drawer,	[ 0.6 -0.3  0. ], opened, cont: [],	|| [drawer2] >>
2. cup1,	cup,	[ 0.6 -0.3  0. ], empty,	|| [cup1] >>
Robot: [0.6 0.3 0.6], closed, rotation: 0, attached: -
User id: 1


Fake object move, normally **Move Actions** are used to move the object.

In [13]:
scene.cup1.position = scene.drawer1.position

In [14]:
scene

Scene info. shape: [4, 4, 4]
0. drawer1,	drawer,	[ 0.2 -0.3  0. ], semi-opened, cont: [],	|| [drawer1] >>
1. drawer2,	drawer,	[ 0.6 -0.3  0. ], opened, cont: [],	|| [drawer2] >>
2. cup1,	cup,	[ 0.2 -0.3  0. ], empty,	|| [cup1] >>
Robot: [0.6 0.3 0.6], closed, rotation: 0, attached: -
User id: 1

In [15]:
scene.drawer1.open()

(True, '')

In [16]:
scene.drawer1.put_in(scene.cup1)

(True, '')

In [17]:
scene.info

Scene info. shape: [4, 4, 4]
0. drawer1,	drawer,	[ 0.2 -0.3  0. ], opened, cont: ['cup1'],	|| [drawer1] >>
1. drawer2,	drawer,	[ 0.6 -0.3  0. ], opened, cont: [],	|| [drawer2] >>
2. cup1,	cup,	[ 0.2 -0.3  0. ], empty,	|| [cup1] >>
Robot: [0.6 0.3 0.6], closed, rotation: 0, attached: -
User id: 1


## Ex.3: Generate scene from dictionary
- Example has stacked objects -> `print_structure()` reveals the structure of an object

E.g. Structure:

```
cup2 -> stacked object on cup1
[cup1] -> stacked object on drawer, [...] - current object
drawer -> ground level
```

In [18]:
scene_dict = {
'objects': {
    'drawer': {'position': np.array([3, 2, 0]),
        'type': 'drawer',
        'graspable': False,
        'pushable': False,
        'free': True,
        'size': 0.2,
        'opened': False,
        'above_str': 'cup1'},
    'cup1': {'position': np.array([3, 1, 0]),
        'type': 'cup',
        'graspable': True,
        'pushable': True,
        'free': True,
        'size': 0.01,
        'full': True,
        'under_str': 'drawer',
        'above_str': 'cup2'},
    'cup2': {'position': np.array([1, 2, 0]),
        'type': 'cup',
        'graspable': True,
        'pushable': True,
        'free': True,
        'full': True,
        'size': 0.01,
        'under_str': 'cup1'}
    },
    'robot': {
        'eef_position': np.array([0,0,0]),
        'gripper_opened': True,
        'eef_rotation': 0,
        'attached': None
    },
    'user': 0
}
scene = Scene(init='from_dict', import_data=scene_dict)

In [19]:
scene.cup1.print_structure()

Structure:
cup2
[cup1]
drawer


In [20]:
scene.cup2.print_structure()

Structure:
[cup2]
cup1
drawer


In [21]:
scene.drawer.print_structure()

Structure:
cup2
cup1
[drawer]


## Ex.3.1:

In [22]:
scene_dict = {
'objects': {
    'drawer': {'position': np.array([3, 2, 0]),
        'type': 'drawer',
        'graspable': False,
        'pushable': False,
        'free': True,
        'size': 0.2,
        'opened': False,
        'contains_list': ['cup1', 'cup2'],
        'above_str': 'cup1'},
    'cup1': {'position': np.array([3, 1, 0]),
        'type': 'cup',
        'graspable': True,
        'pushable': True,
        'free': True,
        'full': True,
        'size': 0.01,
        'under_str': 'drawer',
        'above_str': 'cup2'},
    'cup2': {'position': np.array([1, 2, 0]),
        'type': 'cup',
        'graspable': True,
        'pushable': True,
        'free': True,
        'full': True,
        'size': 0.01,
        'under_str': 'cup1'},
    },
    'robot': {
        'eef_position': np.array([0,0,0]),
        'gripper_opened': True,
        'eef_rotation': 0,
        'attached': None
    },
    'user': 0
}
scene = Scene(init='from_dict', import_data=scene_dict)

In [23]:
scene.cup1.print_structure()

Structure:
cup2
[cup1]
drawer


In [24]:
scene.drawer.contains_list

['cup1', 'cup2']

In [25]:
scene.drawer.contains

In [26]:
scene.collision_free()

True

# Actions
- The layer which users interact with
- Each action has **Target Action** and **Target Object**, in future there might be **Target Measure**.

## Ex.1: Put cup into drawer

In [27]:
s = Scene(init='drawer,cup', random=False)
s.r.eef_position = s.drawer.position
s.info

Scene info. shape: [4, 4, 4]
0. drawer,	drawer,	[ 0.2 -0.3  0. ], closed, cont: [],	|| [drawer] >>
1. cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>
Robot: [ 0.2 -0.3  0. ], opened, rotation: [1. 0. 0. 0.], attached: -
User id: 0


In [28]:
print(Actions.do(s, ('pick_up', 'cup'), ignore_location=True))
s.info

True
Scene info. shape: [4, 4, 4]
0. drawer,	drawer,	[ 0.2 -0.3  0. ], closed, cont: [],	|| [drawer] >>
1. cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>
Robot: [ 0.2 -0.1  0. ], opened, rotation: [1. 0. 0. 0.], attached: cup
User id: 0


In [29]:
Actions.do(s, ('open', 'drawer'), ignore_location=True)

True

In [30]:
print(Actions.do(s, ('put', 'drawer'), ignore_location=True))
s.info

True
Scene info. shape: [4, 4, 4]
0. drawer,	drawer,	[ 0.2 -0.3  0. ], opened, cont: ['cup'],	|| [drawer] >>
1. cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>
Robot: [ 0.2 -0.1  0. ], opened, rotation: [1. 0. 0. 0.], attached: -
User id: 0


## Ex.2: Pour cup one into cup two

In [31]:
s = Scene(init='drawer,cup,cup', random=False)
s.cup.fill()
s.cup.info
s.cup1.info

cup,	cup,	[ 0.2 -0.1  0. ], full,	|| [cup] >>
cup1,	cup,	[0.2 0.1 0. ], empty,	|| [cup1] >>


In [32]:
Actions.do(s, ('pick_up', 'cup'), ignore_location=True, out=True)
Actions.do(s, ('pour', 'cup1'), ignore_location=True, out=True)
s.cup.info
s.cup1.info

('pick_up', 'cup') done!
('pour', 'cup1') done!
cup,	cup,	[ 0.2 -0.1  0. ], full,	|| [cup] >>
cup1,	cup,	[0.2 0.1 0. ], full,	|| [cup1] >>


In [33]:
s.cup1.direction

array([0, 0, 1])

In [36]:
s.r.eef_position

array([0, 1, 0])

In [37]:
s.cup.info
s.cup1.info

cup,	cup,	[ 0.2 -0.1  0. ], full,	|| [cup] >>
cup1,	cup,	[0.2 0.1 0. ], full,	|| [cup1] >>


In [ ]:
s.cup1.rotate([0,0,0,1])
s.info

## Ex.3: Pour cup one into drawer

In [39]:
s = Scene(init='drawer,cup,cup', random=False)
s.cup1.fill()
s.info

Scene info. shape: [4, 4, 4]
0. drawer,	drawer,	[ 0.2 -0.3  0. ], closed, cont: [],	|| [drawer] >>
1. cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>
2. cup1,	cup,	[0.2 0.1 0. ], full,	|| [cup1] >>
Robot: [ 0.2 -0.3  0.6], opened, rotation: [1. 0. 0. 0.], attached: -
User id: 0


In [40]:
Actions.do(s, ('pick_up', 'cup'), ignore_location=True, out=True)
Actions.do(s, ('pour', 'drawer'), ignore_location=True, out=True)
s.cup.info

('pick_up', 'cup') done!
('pour', 'drawer') done!
cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>


In [41]:
s.info

Scene info. shape: [4, 4, 4]
0. drawer,	drawer,	[ 0.2 -0.3  0. ], closed, cont: [],	|| [drawer] >>
1. cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>
2. cup1,	cup,	[0.2 0.1 0. ], full,	|| [cup1] >>
Robot: [ 0.2 -0.1  0. ], opened, rotation: [1. 0. 0. 0.], attached: cup
User id: 0


## Ex.4: Spill the cup

In [42]:
s.cup1.rotate([1,0,0,0])
s.cup.info

cup,	cup,	[ 0.2 -0.1  0. ], empty,	|| [cup] >>


In [43]:
s = Scene(init='drawer,cup,cup')
s.r.eef_position = s.cup1.position
s.info

Scene info. shape: [4, 4, 4]
0. drawer,	drawer,	[0.8 0.1 0. ], closed, cont: [],	|| [drawer] >>
1. cup,	cup,	[0.6 0.3 0. ], full,	|| [cup] >>
2. cup1,	cup,	[0.6 0.1 0. ], empty,	|| [cup1] >>
Robot: [0.6 0.1 0. ], closed, rotation: 1, attached: -
User id: 0


In [44]:
Actions.do(s, ('push','cup'), ignore_location=True, out=True)
s.cup1.position

('push', 'cup') done!


array([2, 2, 0])